// <auto-generated />
using System;
using DhanMarketData.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DhanMarketData.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607072754_RemoveCorruptedPresets")]
    partial class RemoveCorruptedPresets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.ApiCredentials", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotpSeedEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApiCredentials");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.BacktestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacktestDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DiagnosticLogEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeSegment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresetSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrategyPresetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDaysPlanned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDaysProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("Status");

                    b.HasIndex("StrategyPresetId");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.StrategyPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenerConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenerType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StrategyPresets");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Momentum: on a trending Mon/Wed session, a liquid (≥30L/day prior avg), higher-priced (≥₹500) stock that gapped ≥0% breaks above its 30-min opening-range high while holding above a RISING session VWAP (slope 20–50 bps — with-flow but not exhausted) and the opening range was wide (≥1%). Enter next bar's open; SL = min(VWAP, breakout-bar low); HELD TO 15:00 IST (only the stop exits earlier). The day + liquidity + price + OR-width + slope-band + gap selection is the edge; the opening-range break is the trigger. Developed via the offline diagnostic harness on 414 NSE stocks × ~250 days (5-min), fully non-lookahead: raw signal was gross-negative; this stacked config reached ~88 trades, +0.93R/trade (~₹466 at ₹500 risk), 63% win, 11/13 months positive. Mon/Wed avoids Tue/Thu/Fri expiry-day chop (corroborated across two VWAP strategies). IN-SAMPLE — paper-test before live.",
                            IsBuiltIn = true,
                            Name = "VWAP ORB Momentum (Long)",
                            ScreenerConfigJson = "{\n  \"OpeningRangeBars\": 6,\n  \"MinOrWidthPct\": 1.0,\n  \"VwapSlopeLookback\": 3,\n  \"MinVwapSlopeBps\": 20,\n  \"MaxVwapSlopeBps\": 50,\n  \"MinGapPct\": 0,\n  \"WindowStart\": \"09:45:00\",\n  \"WindowEnd\": \"14:00:00\",\n  \"AllowMon\": true,\n  \"AllowTue\": false,\n  \"AllowWed\": true,\n  \"AllowThu\": false,\n  \"AllowFri\": false,\n  \"MinStopDistancePct\": 0.5,\n  \"MaxStopDistancePct\": 0,\n  \"MinPrice\": 500,\n  \"MinAverageDailyVolume\": 3000000,\n  \"VolumeLookbackDays\": 20,\n  \"MinHistoricalDays\": 20\n}",
                            ScreenerType = "vwaporb",
                            StrategyConfigJson = "{\n  \"HardExitTime\": \"15:00:00\",\n  \"ExitOnCloseBelowVwap\": false,\n  \"HardTargetR\": 0,\n  \"RiskPerTrade\": 500,\n  \"CostModelRoundTripPct\": 0.10\n}",
                            StrategyType = "vwaporb",
                            TradingConfigJson = "{\n  \"MarketOpenTime\": \"09:15:00\",\n  \"MarketCloseTime\": \"15:30:00\",\n  \"EntryTime\": \"09:30:00\",\n  \"ExitTime\": \"15:15:00\",\n  \"TargetMultiplier\": 2.5,\n  \"FixedStopLoss\": 500,\n  \"FixedTarget\": 2000,\n  \"RequireCloseAboveDayOpen\": false,\n  \"TrailStepMultiplier\": 2.0,\n  \"MaxTradesPerDay\": 20,\n  \"MaxCapitalPerTrade\": 300000\n}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.TradeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacktestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BreakoutCandleVolMult")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GapPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OrWidthPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PnLPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RvolAtEntry")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Target")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId", "Date");

                    b.HasIndex("BacktestRunId", "ExitReason");

                    b.ToTable("TradeRecords");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.BacktestRun", b =>
                {
                    b.HasOne("DhanMarketData.Persistence.Entities.StrategyPreset", "StrategyPreset")
                        .WithMany()
                        .HasForeignKey("StrategyPresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StrategyPreset");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.TradeRecord", b =>
                {
                    b.HasOne("DhanMarketData.Persistence.Entities.BacktestRun", "BacktestRun")
                        .WithMany("Trades")
                        .HasForeignKey("BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.BacktestRun", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
