// <auto-generated />
using System;
using DhanMarketData.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DhanMarketData.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526202120_RenameTuneEmaGapDownReclaim")]
    partial class RenameTuneEmaGapDownReclaim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.ApiCredentials", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApiCredentials");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.BacktestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacktestDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeSegment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresetSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrategyPresetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDaysPlanned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDaysProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("Status");

                    b.HasIndex("StrategyPresetId");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.StrategyPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenerConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenerType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StrategyPresets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Early-morning unusual volume; enter at 9:30 open with fixed SL/target.",
                            IsBuiltIn = true,
                            Name = "Volume Spike",
                            ScreenerConfigJson = "{\n  \"ScreeningCandleCount\": 3,\n  \"VolumeMultiplier\": 2.0,\n  \"CandleSizeMultiplier\": 3.0\n}",
                            ScreenerType = "volumespike",
                            StrategyConfigJson = "{}",
                            StrategyType = "fixedtarget",
                            TradingConfigJson = "{\n  \"MarketOpenTime\": \"09:15:00\",\n  \"MarketCloseTime\": \"15:30:00\",\n  \"EntryTime\": \"09:30:00\",\n  \"ExitTime\": \"15:15:00\",\n  \"TargetMultiplier\": 2.5,\n  \"FixedStopLoss\": 500,\n  \"FixedTarget\": 2000,\n  \"RequireCloseAboveDayOpen\": false,\n  \"TrailStepMultiplier\": 2.0,\n  \"MaxTradesPerDay\": 2,\n  \"MaxCapitalPerTrade\": 300000\n}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Identify dominance candle in 9:30–10:00 window; enter on next-candle breakout above its high; fixed SL/target.",
                            IsBuiltIn = true,
                            Name = "Dominance Breakout",
                            ScreenerConfigJson = "{\n  \"MinBodyPercent\": 70,\n  \"MaxBodyPercent\": 85,\n  \"MinWickPercent\": 5,\n  \"MinCandleSizeMultiplier\": 1.0,\n  \"MaxCandleSizeMultiplier\": 2.5,\n  \"VolumeMultiplier\": 2.0,\n  \"MinAbsoluteVolume\": 5000,\n  \"MaxMovementMultiplier\": 2.0,\n  \"MaxGapUpPercent\": 2.5,\n  \"MaxGapDownPercent\": 1.0,\n  \"HistoricalDays\": 10,\n  \"EntryBracketStart\": \"09:30:00\",\n  \"EntryBracketEnd\": \"10:00:00\"\n}",
                            ScreenerType = "dominancecandle",
                            StrategyConfigJson = "{}",
                            StrategyType = "breakoutentry",
                            TradingConfigJson = "{\n  \"MarketOpenTime\": \"09:15:00\",\n  \"MarketCloseTime\": \"15:30:00\",\n  \"EntryTime\": \"09:30:00\",\n  \"ExitTime\": \"15:15:00\",\n  \"TargetMultiplier\": 2.5,\n  \"FixedStopLoss\": 500,\n  \"FixedTarget\": 2000,\n  \"RequireCloseAboveDayOpen\": false,\n  \"TrailStepMultiplier\": 2.0,\n  \"MaxTradesPerDay\": 2,\n  \"MaxCapitalPerTrade\": 300000\n}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Same dominance-candle entry as Dominance Breakout, but trailing SL instead of fixed target.",
                            IsBuiltIn = true,
                            Name = "Dominance Trailing",
                            ScreenerConfigJson = "{\n  \"MinBodyPercent\": 70,\n  \"MaxBodyPercent\": 85,\n  \"MinWickPercent\": 5,\n  \"MinCandleSizeMultiplier\": 1.0,\n  \"MaxCandleSizeMultiplier\": 2.5,\n  \"VolumeMultiplier\": 2.0,\n  \"MinAbsoluteVolume\": 5000,\n  \"MaxMovementMultiplier\": 2.0,\n  \"MaxGapUpPercent\": 2.5,\n  \"MaxGapDownPercent\": 1.0,\n  \"HistoricalDays\": 10,\n  \"EntryBracketStart\": \"09:30:00\",\n  \"EntryBracketEnd\": \"10:00:00\"\n}",
                            ScreenerType = "dominancecandle",
                            StrategyConfigJson = "{}",
                            StrategyType = "trailingstop",
                            TradingConfigJson = "{\n  \"MarketOpenTime\": \"09:15:00\",\n  \"MarketCloseTime\": \"15:30:00\",\n  \"EntryTime\": \"09:30:00\",\n  \"ExitTime\": \"15:15:00\",\n  \"TargetMultiplier\": 2.5,\n  \"FixedStopLoss\": 500,\n  \"FixedTarget\": 2000,\n  \"RequireCloseAboveDayOpen\": false,\n  \"TrailStepMultiplier\": 2.0,\n  \"MaxTradesPerDay\": 2,\n  \"MaxCapitalPerTrade\": 300000\n}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clean gap-up + opening-range structure; enter on break above OR.High inside the execution window.",
                            IsBuiltIn = true,
                            Name = "Opening Range Breakout",
                            ScreenerConfigJson = "{\n  \"MinGapPercent\": 0.8,\n  \"MaxGapPercent\": 10.0,\n  \"MaxUpperWickPercent\": 80,\n  \"MinVolumeMultiplier\": 1.5,\n  \"CleanCandleCount\": 2,\n  \"OpeningRangeMinutes\": 10,\n  \"ObservationEndTime\": \"09:25:00\",\n  \"ExecutionWindowStart\": \"09:40:00\",\n  \"ExecutionWindowEnd\": \"09:40:00\",\n  \"HistoricalDaysForAverage\": 10,\n  \"MaxCandleSizeMultiplier\": 3.0\n}",
                            ScreenerType = "openingrange",
                            StrategyConfigJson = "{}",
                            StrategyType = "openingrange",
                            TradingConfigJson = "{\n  \"MarketOpenTime\": \"09:15:00\",\n  \"MarketCloseTime\": \"15:30:00\",\n  \"EntryTime\": \"09:30:00\",\n  \"ExitTime\": \"15:15:00\",\n  \"TargetMultiplier\": 2.5,\n  \"FixedStopLoss\": 500,\n  \"FixedTarget\": 2000,\n  \"RequireCloseAboveDayOpen\": false,\n  \"TrailStepMultiplier\": 2.0,\n  \"MaxTradesPerDay\": 2,\n  \"MaxCapitalPerTrade\": 300000\n}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quiet, ATR-normalized gap-downs on liquid trending stocks; confirmation-candle entry inside 09:30–10:15 window; mean-reversion long.",
                            IsBuiltIn = true,
                            Name = "Gap Fade (Long)",
                            ScreenerConfigJson = "{\n  \"MinGapAtrRatio\": 0.20,\n  \"MaxGapAtrRatio\": 0.60,\n  \"RequirePartialGap\": true,\n  \"RequireUnfilledAtEntry\": true,\n  \"MaxOpeningVolumeMultiplier\": 0.8,\n  \"MinAbsoluteVolume\": 1000,\n  \"VolumeAverageDays\": 10,\n  \"MinAverageDailyVolume\": 500000,\n  \"MinPrice\": 100,\n  \"RequireUptrend\": true,\n  \"SmaPeriod\": 20,\n  \"AtrPeriod\": 14,\n  \"MinHistoricalDays\": 25,\n  \"MaxStopLossPercent\": 1.0\n}",
                            ScreenerType = "gapfade",
                            StrategyConfigJson = "{\n  \"EntryWindowStart\": \"09:30:00\",\n  \"EntryWindowEnd\": \"10:15:00\",\n  \"RequireConfirmationCandle\": true,\n  \"TimeExit\": \"12:30:00\"\n}",
                            StrategyType = "gapfadelong",
                            TradingConfigJson = "{\n  \"MarketOpenTime\": \"09:15:00\",\n  \"MarketCloseTime\": \"15:30:00\",\n  \"EntryTime\": \"09:30:00\",\n  \"ExitTime\": \"15:15:00\",\n  \"TargetMultiplier\": 2.5,\n  \"FixedStopLoss\": 500,\n  \"FixedTarget\": 2000,\n  \"RequireCloseAboveDayOpen\": false,\n  \"TrailStepMultiplier\": 2.0,\n  \"MaxTradesPerDay\": 2,\n  \"MaxCapitalPerTrade\": 300000\n}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "15-min ORB on F&O-eligible NSE stocks, filtered by cash RVOL and confirmed by futures OI direction. Long buildup = full size; short covering = half size. v1 uses 5-min timeframe (15-min OI delta requires multi-candle OR), MinScoreThreshold instead of cross-stock top-N ranking, and includes spec §12 cost model (0.10% RT).",
                            IsBuiltIn = true,
                            Name = "Volume Confluence Breakout (Long)",
                            ScreenerConfigJson = "{\n  \"OpeningRangeMinutes\": 15,\n  \"DojiThreshold\": 0.10,\n  \"RvolLookbackDays\": 14,\n  \"MinRvol\": 1.0,\n  \"MinScoreThreshold\": 1.0,\n  \"RequireFnoOnly\": true,\n  \"MinPrice\": 50,\n  \"MinAvgRupeeVolume\": 1000000000,\n  \"MinAtrPercent\": 1.0,\n  \"MaxYesterdayRangePct\": 9.0,\n  \"AtrLookback\": 14,\n  \"RequireOiConfluence\": false,\n  \"MinOiDeltaPercent\": 1.0,\n  \"SkipDayIfIndiaVixAbove\": 25.0,\n  \"SkipDayIfNiftyGapPct\": 2.0,\n  \"MinHistoricalDays\": 28,\n  \"SkipTuesday\": true,\n  \"MinGapPct\": -1.5\n}",
                            ScreenerType = "rvolorb",
                            StrategyConfigJson = "{\n  \"AtrStopMultiplier\": 0.30,\n  \"NoFillCutoff\": \"13:00:00\",\n  \"EntryNotBefore\": \"10:00:00\",\n  \"EntryNotAfter\": \"10:30:00\",\n  \"MinBreakoutVolMult\": 0.5,\n  \"ExitTime\": \"14:30:00\",\n  \"DayMultiplierMon\": 1.0,\n  \"DayMultiplierTue\": 1.0,\n  \"DayMultiplierWed\": 1.0,\n  \"DayMultiplierThu\": 1.0,\n  \"DayMultiplierFri\": 1.0,\n  \"CostModelRoundTripPct\": 0.10\n}",
                            StrategyType = "confluenceorblong",
                            TradingConfigJson = "{\n  \"MarketOpenTime\": \"09:15:00\",\n  \"MarketCloseTime\": \"15:30:00\",\n  \"EntryTime\": \"09:30:00\",\n  \"ExitTime\": \"14:30:00\",\n  \"TargetMultiplier\": 1.0,\n  \"FixedStopLoss\": 1000,\n  \"FixedTarget\": 0,\n  \"RequireCloseAboveDayOpen\": false,\n  \"TrailStepMultiplier\": 1.0,\n  \"MaxTradesPerDay\": 10,\n  \"MaxCapitalPerTrade\": 100000\n}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Buy-the-dip: uptrending stocks (2–10% above their 20-day SMA) that gapped DOWN ≥1.5%, entered when price reclaims the 9-EMA intraday (pullback touch + bullish close), filtered to moderate trend strength (ADX ≤ 25 — high ADX = exhausted move). SL at trigger low, 1.5R target, hard exit 15:00 IST. The gap-down-in-uptrend is the stock selection; the 9-EMA reclaim is the trigger. Tuned on 500 NSE stocks × 250 days (net +52k, PF ~4.5, 77% win, max drawdown 3% — IN-SAMPLE, paper-test before live; the ADX≤25 cut is data-selected and will regress somewhat).",
                            IsBuiltIn = true,
                            Name = "EMA Gap-Down Reclaim (Long)",
                            ScreenerConfigJson = "{\n  \"FastEmaPeriod\": 9,\n  \"SlowEmaPeriod\": 20,\n  \"SlopeLookback\": 5,\n  \"MinEmaDistanceAtr\": 0.3,\n  \"MaxEmaDistanceAtr\": 1.5,\n  \"MinDailyAtrPct\": 1.5,\n  \"DailyAtrPeriod\": 14,\n  \"MinDailyTrendPct\": 2.0,\n  \"MaxDailyTrendPct\": 10.0,\n  \"DailyTrendSmaPeriod\": 20,\n  \"IntradayAtrPeriod\": 14,\n  \"MorningStart\": \"10:00:00\",\n  \"MorningEnd\": \"11:00:00\",\n  \"AfternoonStart\": \"13:30:00\",\n  \"AfternoonEnd\": \"14:00:00\",\n  \"RequireEngulfing\": true,\n  \"MinStopDistancePct\": 0.45,\n  \"MaxStopDistancePct\": 1.5,\n  \"MinRvol\": 0,\n  \"RvolLookbackDays\": 10,\n  \"MinAdx\": 0,\n  \"MaxAdx\": 25,\n  \"AdxPeriod\": 14,\n  \"MinTriggerVolMult\": 0,\n  \"MinGapPct\": 0,\n  \"MaxGapPct\": 5,\n  \"MaxEntryGapPct\": -1.5,\n  \"MinPrice\": 100,\n  \"MinAverageDailyVolume\": 500000,\n  \"MinHistoricalDays\": 25\n}",
                            ScreenerType = "emapullback",
                            StrategyConfigJson = "{\n  \"RiskRewardRatio\": 1.5,\n  \"HardExitTime\": \"15:00:00\",\n  \"UseTrailingStop\": false,\n  \"TrailActivateR\": 1.0,\n  \"TrailGapR\": 1.0,\n  \"TrailHardTargetR\": 0,\n  \"CostModelRoundTripPct\": 0.10\n}",
                            StrategyType = "emapullback",
                            TradingConfigJson = "{\n  \"MarketOpenTime\": \"09:15:00\",\n  \"MarketCloseTime\": \"15:30:00\",\n  \"EntryTime\": \"09:30:00\",\n  \"ExitTime\": \"15:15:00\",\n  \"TargetMultiplier\": 2.5,\n  \"FixedStopLoss\": 500,\n  \"FixedTarget\": 2000,\n  \"RequireCloseAboveDayOpen\": false,\n  \"TrailStepMultiplier\": 2.0,\n  \"MaxTradesPerDay\": 2,\n  \"MaxCapitalPerTrade\": 300000\n}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.TradeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacktestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BreakoutCandleVolMult")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GapPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OrWidthPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PnLPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RvolAtEntry")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Target")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId", "Date");

                    b.HasIndex("BacktestRunId", "ExitReason");

                    b.ToTable("TradeRecords");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.BacktestRun", b =>
                {
                    b.HasOne("DhanMarketData.Persistence.Entities.StrategyPreset", "StrategyPreset")
                        .WithMany()
                        .HasForeignKey("StrategyPresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StrategyPreset");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.TradeRecord", b =>
                {
                    b.HasOne("DhanMarketData.Persistence.Entities.BacktestRun", "BacktestRun")
                        .WithMany("Trades")
                        .HasForeignKey("BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.BacktestRun", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
