// <auto-generated />
using System;
using DhanMarketData.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DhanMarketData.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502183443_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.ApiCredentials", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApiCredentials");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.BacktestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacktestDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeSegment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresetSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrategyPresetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDaysPlanned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDaysProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("Status");

                    b.HasIndex("StrategyPresetId");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.StrategyPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenerConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenerType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StrategyPresets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Early-morning unusual volume; enter at 9:30 open with fixed SL/target.",
                            IsBuiltIn = true,
                            Name = "Volume Spike",
                            ScreenerConfigJson = "{\n  \"ScreeningCandleCount\": 3,\n  \"VolumeMultiplier\": 2.0,\n  \"CandleSizeMultiplier\": 3.0\n}",
                            ScreenerType = "volumespike",
                            StrategyConfigJson = "{}",
                            StrategyType = "fixedtarget",
                            TradingConfigJson = "{\n  \"MarketOpenTime\": \"09:15:00\",\n  \"MarketCloseTime\": \"15:30:00\",\n  \"EntryTime\": \"09:30:00\",\n  \"ExitTime\": \"15:15:00\",\n  \"TargetMultiplier\": 2.5,\n  \"FixedStopLoss\": 500,\n  \"FixedTarget\": 2000,\n  \"RequireCloseAboveDayOpen\": false,\n  \"TrailStepMultiplier\": 2.0,\n  \"MaxTradesPerDay\": 2,\n  \"MaxCapitalPerTrade\": 300000\n}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Identify dominance candle in 9:30–10:00 window; enter on next-candle breakout above its high; fixed SL/target.",
                            IsBuiltIn = true,
                            Name = "Dominance Breakout",
                            ScreenerConfigJson = "{\n  \"MinBodyPercent\": 70,\n  \"MaxBodyPercent\": 85,\n  \"MinWickPercent\": 5,\n  \"MinCandleSizeMultiplier\": 1.0,\n  \"MaxCandleSizeMultiplier\": 2.5,\n  \"VolumeMultiplier\": 2.0,\n  \"MinAbsoluteVolume\": 5000,\n  \"MaxMovementMultiplier\": 2.0,\n  \"MaxGapUpPercent\": 2.5,\n  \"MaxGapDownPercent\": 1.0,\n  \"HistoricalDays\": 10,\n  \"EntryBracketStart\": \"09:30:00\",\n  \"EntryBracketEnd\": \"10:00:00\"\n}",
                            ScreenerType = "dominancecandle",
                            StrategyConfigJson = "{}",
                            StrategyType = "breakoutentry",
                            TradingConfigJson = "{\n  \"MarketOpenTime\": \"09:15:00\",\n  \"MarketCloseTime\": \"15:30:00\",\n  \"EntryTime\": \"09:30:00\",\n  \"ExitTime\": \"15:15:00\",\n  \"TargetMultiplier\": 2.5,\n  \"FixedStopLoss\": 500,\n  \"FixedTarget\": 2000,\n  \"RequireCloseAboveDayOpen\": false,\n  \"TrailStepMultiplier\": 2.0,\n  \"MaxTradesPerDay\": 2,\n  \"MaxCapitalPerTrade\": 300000\n}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Same dominance-candle entry as Dominance Breakout, but trailing SL instead of fixed target.",
                            IsBuiltIn = true,
                            Name = "Dominance Trailing",
                            ScreenerConfigJson = "{\n  \"MinBodyPercent\": 70,\n  \"MaxBodyPercent\": 85,\n  \"MinWickPercent\": 5,\n  \"MinCandleSizeMultiplier\": 1.0,\n  \"MaxCandleSizeMultiplier\": 2.5,\n  \"VolumeMultiplier\": 2.0,\n  \"MinAbsoluteVolume\": 5000,\n  \"MaxMovementMultiplier\": 2.0,\n  \"MaxGapUpPercent\": 2.5,\n  \"MaxGapDownPercent\": 1.0,\n  \"HistoricalDays\": 10,\n  \"EntryBracketStart\": \"09:30:00\",\n  \"EntryBracketEnd\": \"10:00:00\"\n}",
                            ScreenerType = "dominancecandle",
                            StrategyConfigJson = "{}",
                            StrategyType = "trailingstop",
                            TradingConfigJson = "{\n  \"MarketOpenTime\": \"09:15:00\",\n  \"MarketCloseTime\": \"15:30:00\",\n  \"EntryTime\": \"09:30:00\",\n  \"ExitTime\": \"15:15:00\",\n  \"TargetMultiplier\": 2.5,\n  \"FixedStopLoss\": 500,\n  \"FixedTarget\": 2000,\n  \"RequireCloseAboveDayOpen\": false,\n  \"TrailStepMultiplier\": 2.0,\n  \"MaxTradesPerDay\": 2,\n  \"MaxCapitalPerTrade\": 300000\n}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clean gap-up + opening-range structure; enter on break above OR.High inside the execution window.",
                            IsBuiltIn = true,
                            Name = "Opening Range Breakout",
                            ScreenerConfigJson = "{\n  \"MinGapPercent\": 0.8,\n  \"MaxGapPercent\": 10.0,\n  \"MaxUpperWickPercent\": 80,\n  \"MinVolumeMultiplier\": 1.5,\n  \"CleanCandleCount\": 2,\n  \"OpeningRangeMinutes\": 10,\n  \"ObservationEndTime\": \"09:25:00\",\n  \"ExecutionWindowStart\": \"09:40:00\",\n  \"ExecutionWindowEnd\": \"09:40:00\",\n  \"HistoricalDaysForAverage\": 10,\n  \"MaxCandleSizeMultiplier\": 3.0\n}",
                            ScreenerType = "openingrange",
                            StrategyConfigJson = "{}",
                            StrategyType = "openingrange",
                            TradingConfigJson = "{\n  \"MarketOpenTime\": \"09:15:00\",\n  \"MarketCloseTime\": \"15:30:00\",\n  \"EntryTime\": \"09:30:00\",\n  \"ExitTime\": \"15:15:00\",\n  \"TargetMultiplier\": 2.5,\n  \"FixedStopLoss\": 500,\n  \"FixedTarget\": 2000,\n  \"RequireCloseAboveDayOpen\": false,\n  \"TrailStepMultiplier\": 2.0,\n  \"MaxTradesPerDay\": 2,\n  \"MaxCapitalPerTrade\": 300000\n}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.TradeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacktestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PnL")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PnLPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Target")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId", "Date");

                    b.HasIndex("BacktestRunId", "ExitReason");

                    b.ToTable("TradeRecords");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.BacktestRun", b =>
                {
                    b.HasOne("DhanMarketData.Persistence.Entities.StrategyPreset", "StrategyPreset")
                        .WithMany()
                        .HasForeignKey("StrategyPresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StrategyPreset");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.TradeRecord", b =>
                {
                    b.HasOne("DhanMarketData.Persistence.Entities.BacktestRun", "BacktestRun")
                        .WithMany("Trades")
                        .HasForeignKey("BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("DhanMarketData.Persistence.Entities.BacktestRun", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
